### PR TITLE
Feature/instagram stalk

### PR DESCRIPTION
**Pull request by almanalfaruq**

### CODE REVIEW

**Review by axellageraldinc — CHANGES_REQUESTED** [review]
Hi thanks for the work.
I have e change request, please give `@Service` annotation above InstagramServiceImpl

**Review by axellageraldinc — COMMENTED** [review]
Would you tell me the reason why you moved the INSTAGRAM_URL to InstagramService interface?
Because I think it's okay to just declare INSTAGRAM_URL as static variable inside InstagramServiceImpl, after all it's static so it'll be instantiated once no matter what.

**Comment by almanalfaruq** [comment]
Ohh, sorry I think it'll be easy to manage if that variable was declared in the InstagramService interface.

**Review by axellageraldinc — CHANGES_REQUESTED** [review]
Can you tell me why you think it'll be easy to manage?

**Comment by axellageraldinc** [comment]
Oh one more thing, can you provide a response which tells the users if the username doesn't exist, the username has a private account, or the username doesn't have any posts yet?

**Comment by almanalfaruq** [comment]
Forgot about that, wait a sec

**Comment by axellageraldinc** [comment]
Yeah I just remembered. Is there any way to know if there’s an API error? Such as api call limit excedded, or API Key expired, or need new api version. If that's not possible it's okay, just confirm this message then I'll merge your pull request

**Comment by axellageraldinc** [comment]
I'll just merge this pull request then deploy

**Pull request merged**
